# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions
alias ls='ls -G'
alias ll='ls -l'
alias la='ls -la'
alias lh='ls -lh'
alias grep='grep --color=auto'

export EDITOR="vim"
export SVN_EDITOR="vim"
export HISTCONTROL=ignoredups
  
source .bashrc_ps
